services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postg
      POSTGRES_PASSWORD: postg
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: