version: "1"
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - redis
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: ["pnpm", "start:dev"]

  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - "6380:6379"
