services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5431:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
# services:
#   db:
#     image: mysql:8.0
#     container_name: mysql-container2
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: myuser
#       MYSQL_PASSWORD: mypassword
#     ports:
#       - '3306:3306'
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
